# tf.constant

**tf.constant:** is a function used to create a constant tensor, which is a type of tensor that holds a constant value throughout its lifetime. The value of a constant tensor is set at creation time and cannot be changed later.

* **Tensors:** are multi-dimensional arrays.
* **Arrays:** are ordered, mutable and sequential data-structure.

**Zero-Dimensional Tensor:** also known as scalar. Shape is Zero or No Shape.

```python
Examples:
3, 4, 88, 6
```


In [15]:
import tensorflow as tf

zero_dimensional_tensor = tf.constant(value=3)
print(zero_dimensional_tensor)

tf.Tensor(3, shape=(), dtype=int32)


**1-Dimensional Tensor:** contains multiple Zero-Dimensional Tensor. Shape: (m, ) m ➾ total number of rows, No columns.
```python
Examples:
[3, 4, 88, 6]
```

In [16]:
one_dimensional_tensor = tf.constant(value=[3, 4, 88, 6])
print(one_dimensional_tensor)

tf.Tensor([ 3  4 88  6], shape=(4,), dtype=int32)


**2-Dimensional Tensor:** contains multiple 1-Dimensional Tensor. Shape: `(m,n)` **m** ➾ total number of rows, **n** ➾ total number of columns.
```python
[3, 4, 5, 6]
[4, 5, 6, 7]
[5, 6, 7, 8]
[6, 7, 8, 9]
```

In [17]:
two_dimensional_tensor = tf.constant(value=[[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9]])
print(two_dimensional_tensor)

tf.Tensor(
[[3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]], shape=(4, 4), dtype=int32)


**3-Dimensional Tensor:** contains multiple 2-Dimensional Tensor.
```python
[
   [[3, 4, 5, 6]
    [4, 5, 6, 7]
    [5, 6, 7, 8]
    [6, 7, 8, 9]],

   [[3, 4, 5, 6]
    [4, 5, 6, 7]
    [5, 6, 7, 8]
    [6, 7, 8, 9]]
]
```

In [19]:
three_dimensional_tensor = tf.constant(value=[
    [[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9]],
    [[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9]]
])
print(three_dimensional_tensor)

tf.Tensor(
[[[3 4 5 6]
  [4 5 6 7]
  [5 6 7 8]
  [6 7 8 9]]

 [[3 4 5 6]
  [4 5 6 7]
  [5 6 7 8]
  [6 7 8 9]]], shape=(2, 4, 4), dtype=int32)


**4-Dimensional Tensor:** contains multiple 3-Dimensional Tensor.
```python
[
   [[3, 4, 5, 6]
    [4, 5, 6, 7]
    [5, 6, 7, 8]
    [6, 7, 8, 9],

    [3, 4, 5, 6]
    [4, 5, 6, 7]
    [5, 6, 7, 8]
    [6, 7, 8, 9]],

    [[3, 4, 5, 6]
    [4, 5, 6, 7]
    [5, 6, 7, 8]
    [6, 7, 8, 9],

    [3, 4, 5, 6]
    [4, 5, 6, 7]
    [5, 6, 7, 8]
    [6, 7, 8, 9]]
]
```

In [23]:
four_dimensional_tensor = tf.constant(value=[
    [[[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9]],
     [[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9]]],

     [[[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9]],
     [[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9]]],
])
print(four_dimensional_tensor)

tf.Tensor(
[[[[3 4 5 6]
   [4 5 6 7]
   [5 6 7 8]
   [6 7 8 9]]

  [[3 4 5 6]
   [4 5 6 7]
   [5 6 7 8]
   [6 7 8 9]]]


 [[[3 4 5 6]
   [4 5 6 7]
   [5 6 7 8]
   [6 7 8 9]]

  [[3 4 5 6]
   [4 5 6 7]
   [5 6 7 8]
   [6 7 8 9]]]], shape=(2, 2, 4, 4), dtype=int32)


# tf.cast
**tf.cast:** is a function used to cast a tensor from one data type to another. It doesn't change the underlying value, but it changes the interpretation of the data.

In [29]:
new_tensor = tf.constant(value=[23,45,00,5,9,0])
print(new_tensor)

casted_to_float = tf.cast(x=new_tensor, dtype=tf.float16)
print(casted_to_float)

casted_to_bool = tf.cast(x=new_tensor, dtype=tf.bool)
print(casted_to_bool)


tf.Tensor([23 45  0  5  9  0], shape=(6,), dtype=int32)
tf.Tensor([23. 45.  0.  5.  9.  0.], shape=(6,), dtype=float16)
tf.Tensor([ True  True False  True  True False], shape=(6,), dtype=bool)


# Indexing

In [30]:
new_tensor = tf.constant(value=[23,45,00,5,9,0])
print(new_tensor)

tf.Tensor([23 45  0  5  9  0], shape=(6,), dtype=int32)


In [31]:
new_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=23>

In [32]:
new_tensor[3]

<tf.Tensor: shape=(), dtype=int32, numpy=5>

# Slicing

In [33]:
new_tensor[:]

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([23, 45,  0,  5,  9,  0], dtype=int32)>

In [34]:
new_tensor[::2]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([23,  0,  9], dtype=int32)>